@url=http://localhost:3001
@json=Content-Type: application/json
@token=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzhhZDRjMDhhMzdjZjc4NGMxMDA1OSIsImlhdCI6MTY5MTExMTQwOCwiZXhwIjoxNjkzNzAzNDA4fQ.JnDzARUL11R3hWY08TvbUjQ5gtK8M4CKF_slSCf-wZ8

### 查询所有用户
get {{url}}/users
{{json}}

### 注册
post {{url}}/createuser
# Content-Type: application/json
{{json}}

{
  "username": "rikusrocks3@gmail.com",
  "password": "12345678"
}

### 登录
post {{url}}/login
{{json}}

{
  "username": "rikusrocks2@gmail.com",
  "password": "12345678"
}

###
get {{url}}/profile
{{token}}

### createForm

post {{url}}/createform
{{json}}
{{token}}

{
  "form" : {
    "formId": "64c8ae2b08a37cf784c10067f1",
    "title":"title",
    "questions":[{
        "id": "64c8ae2b08a37cf784c10067q1",
        "description":"the first question",
        "questionsType": "text",
        "response": "",
        "maxRate": 0,
        "minRate": 0
    }],
    "timestamp": 0,
    "endtime":0
}
}

### getForm
get {{url}}/getuserforms
{{json}}
{{token}}

### updateForm
post {{url}}/updateForm
{{json}}

{
    "formId": "64c8ae2b08a37cf784c10067f1",
    "title":"title",
    "questions":[{
        "id": "64c8ae2b08a37cf784c10067q1",
        "description":"the first question",
        "questionsType": "text",
        "response": "",
        "maxRate": 0,
        "minRate": 0
    },
    {
        "id": "64c8ae2b08a37cf784c10067q2",
        "description":"the second question",
        "questionsType": "rate",
        "response": "",
        "maxRate": 0,
        "minRate": 0
    }
    ],
    "timestamp": 0
}

### deleteForm
post {{url}}/deleteForm
{{json}}

{
  "userId" : "64c8ae2b08a37cf784c10067",
  "formId" : "64c8ae2b08a37cf784c10067f1",
  "status" : "savedForms"
}