@url=http://localhost:3001
@json=Content-Type: application/json

###

get {{url}}

###
post {{url}}

### 查询所有用户
get {{url}}/users
{{json}}
### 注册
post {{url}}/createuser
# Content-Type: application/json
{{json}}

{
  "username": "rikusrocks3@gmail.com",
  "password": "12345678"
}

### 登录
post {{url}}/login
{{json}}

{
  "username": "user4",
  "password": "123456"
}

###
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzMzZjY2ZTE3ZjEyYzI4OWNmZWEwYSIsImlhdCI6MTY5MDYwMjc3M30.vRg5VTOTeqZ-7BVeGJOkNg6UQ6WCeVt2e3clh2P0fqA


### createForm

post {{url}}/createform
{{json}}

{
  "id" : "64c8ae2b08a37cf784c10067",
  "form" : {
    "formId": "64c8ae2b08a37cf784c10067f1",
    "title":"title",
    "questions":[{
        "id": "64c8ae2b08a37cf784c10067q1",
        "description":"the first question",
        "questionsType": "text",
        "response": "",
        "maxRate": 0,
        "minRate": 0
    }],
    "timestamp": 0,
    "endtime":0
}
}

### getForm
post {{url}}/getuserforms
{{json}}

{
  "id" : "64c8a9d3c04db2b36ed6f849"
}

### updateForm
post {{url}}/updateForm
{{json}}

{
    "formId": "64c8ae2b08a37cf784c10067f1",
    "title":"title",
    "questions":[{
        "id": "64c8ae2b08a37cf784c10067q1",
        "description":"the first question",
        "questionsType": "text",
        "response": "",
        "maxRate": 0,
        "minRate": 0
    },
    {
        "id": "64c8ae2b08a37cf784c10067q2",
        "description":"the second question",
        "questionsType": "rate",
        "response": "",
        "maxRate": 0,
        "minRate": 0
    }
    ],
    "timestamp": 0
}

### deleteForm
post {{url}}/deleteForm
{{json}}

{
  "userId" : "64c8ae2b08a37cf784c10067",
  "formId" : "64c8ae2b08a37cf784c10067f1",
  "status" : "savedForms"
}